// ============================================
// KARAKULI — Shared Schedule & Tutor Data
// Edit this file to update the schedule for ALL clients.
// ============================================

const SCHEDULE = [
  {
    id: "math-kate-tue-17",
    subject: "Math",
    icon: "\u{1F9EE}",
    tutor: "Kate K.",
    tutorPhoto: "kate.jpg",
    day: "Tuesday",
    time: "5:00 PM",
    duration: 45,
    ageGroup: "7-10",
    credits: 25,
    spotsLeft: 2,
    maxSpots: 3,
    description: "Logical thinking through puzzles and games. No boring drills!",
  },
  {
    id: "math-kate-thu-17",
    subject: "Math",
    icon: "\u{1F9EE}",
    tutor: "Kate K.",
    tutorPhoto: "kate.jpg",
    day: "Thursday",
    time: "5:00 PM",
    duration: 45,
    ageGroup: "7-10",
    credits: 25,
    spotsLeft: 1,
    maxSpots: 3,
    description: "Logical thinking through puzzles and games. No boring drills!",
  },
  {
    id: "chess-david-mon-16",
    subject: "Chess",
    icon: "\u265F\uFE0F",
    tutor: "David R.",
    tutorPhoto: "david.jpg",
    day: "Monday",
    time: "4:00 PM",
    duration: 45,
    ageGroup: "6-12",
    credits: 25,
    spotsLeft: 2,
    maxSpots: 3,
    description: "From first moves to strategy. Every game is a lesson.",
  },
  {
    id: "chess-david-wed-16",
    subject: "Chess",
    icon: "\u265F\uFE0F",
    tutor: "David R.",
    tutorPhoto: "david.jpg",
    day: "Wednesday",
    time: "4:00 PM",
    duration: 45,
    ageGroup: "6-12",
    credits: 25,
    spotsLeft: 3,
    maxSpots: 3,
    description: "From first moves to strategy. Every game is a lesson.",
  },
  {
    id: "art-artem-sat-11",
    subject: "Art & Anime Drawing",
    icon: "\u{1F3A8}",
    tutor: "Artem T.",
    tutorPhoto: "artem.jpg",
    day: "Saturday",
    time: "11:00 AM",
    duration: 45,
    ageGroup: "5-12",
    credits: 25,
    spotsLeft: 1,
    maxSpots: 3,
    description: "Learn to draw your favorite characters. Anime, manga, and more.",
  },
  {
    id: "coding-antonia-fri-17",
    subject: "Coding",
    icon: "\u{1F4BB}",
    tutor: "Antonia S.",
    tutorPhoto: "antonia.jpg",
    day: "Friday",
    time: "5:00 PM",
    duration: 45,
    ageGroup: "8-12",
    credits: 25,
    spotsLeft: 2,
    maxSpots: 3,
    description: "Build real games and apps. No experience needed.",
  },
  {
    id: "english-kate-wed-10",
    subject: "English",
    icon: "\u{1F1EC}\u{1F1E7}",
    tutor: "Kate K.",
    tutorPhoto: "kate.jpg",
    day: "Wednesday",
    time: "10:00 AM",
    duration: 45,
    ageGroup: "5-9",
    credits: 25,
    spotsLeft: 3,
    maxSpots: 3,
    description: "Speaking, reading, and confidence \u2014 through stories and play.",
  },
  {
    id: "music-artem-sun-12",
    subject: "Music",
    icon: "\u{1F3B5}",
    tutor: "Artem T.",
    tutorPhoto: "artem.jpg",
    day: "Sunday",
    time: "12:00 PM",
    duration: 45,
    ageGroup: "5-12",
    credits: 25,
    spotsLeft: 2,
    maxSpots: 3,
    description: "Explore rhythm, melody, and making music together.",
  },
];

const TUTORS = [
  {
    name: "Kate K.",
    photo: "kate.jpg",
    subjects: ["Math", "English"],
    bio: "5+ years teaching kids math and English. Turns 'I hate math' into 'Can we do one more?'",
    languages: ["English", "Russian"],
    color: "#4AA8E0",
  },
  {
    name: "David R.",
    photo: "david.jpg",
    subjects: ["Chess"],
    bio: "Chess coach and tournament player. Makes every game a learning moment.",
    languages: ["English", "Hebrew"],
    color: "#5BBD6B",
  },
  {
    name: "Artem T.",
    photo: "artem.jpg",
    subjects: ["Art & Anime Drawing", "Music"],
    bio: "Artist and musician. Helps kids discover creativity they didn't know they had.",
    languages: ["English", "Russian"],
    color: "#E85A3A",
  },
  {
    name: "Antonia S.",
    photo: "antonia.jpg",
    subjects: ["Coding", "Math"],
    bio: "Software developer turned teacher. Kids build real games in every class.",
    languages: ["English", "Spanish"],
    color: "#9B59B6",
  },
];
